# Generated by Django 5.2.8 on 2025-11-29 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_academico', '0002_career_faculty_course_career_faculty_profile_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='career',
            field=models.ForeignKey(blank=True, help_text='For student profiles, the career they are enrolled in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='sistema_academico.career'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role determines permissions for this specific profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='sistema_academico.role'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
