# Generated by Django 5.2.8 on 2025-11-29 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_academico', '0003_move_role_to_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_type',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role__name__in': ['Student', 'Undergraduate Student', 'Graduate Student', 'PhD Student', 'PhD Candidate']}, on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to='sistema_academico.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(help_text='Role determines the profile type and permissions', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='sistema_academico.role'),
        ),
        migrations.AlterField(
            model_name='section',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'role__name__in': ['Professor', 'Associate Professor', 'Full Professor', 'Teaching Assistant', 'Adjunct Professor', 'Visiting Professor']}, on_delete=django.db.models.deletion.RESTRICT, related_name='teaching_sections', to='sistema_academico.profile'),
        ),
    ]
