# Generated by Django 5.2.8 on 2025-12-02 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_academico', '0004_remove_profile_type_use_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['Professor', 'Associate Professor', 'Full Professor', 'Teaching Assistant', 'Adjunct Professor', 'Visiting Professor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_enrollments', to='sistema_academico.profile'),
        ),
    ]
